spring.application.name=CarMcQueen
spring.profiles.active=dev

server.address=0.0.0.0
server.port=8080

# Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka}
