server.port=8081
spring.application.name=gateway

# ── RUTAS DEL GATEWAY ────────────────────────────────
# Todas las peticiones /api/** se redirigen al microservicio CarMcQueen
spring.cloud.gateway.routes[0].id=carmcqueen-service
spring.cloud.gateway.routes[0].uri=lb://CarMcQueen
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# Redirigir también la documentación Swagger
spring.cloud.gateway.routes[1].id=carmcqueen-doc
spring.cloud.gateway.routes[1].uri=lb://CarMcQueen
spring.cloud.gateway.routes[1].predicates[0]=Path=/doc/**

spring.cloud.gateway.routes[2].id=carmcqueen-openapi
spring.cloud.gateway.routes[2].uri=lb://CarMcQueen
spring.cloud.gateway.routes[2].predicates[0]=Path=/v3/api-docs/**

# ── EUREKA ───────────────────────────────────────────
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka}

spring.cloud.gateway.forwarded.enabled=false
management.endpoints.web.exposure.include=health,info
